/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/docs/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as graphql from "@nestjs/graphql";
import * as apollo from "apollo-server-express";
import * as nestAccessControl from "nest-access-control";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { CreateClassRoomArgs } from "./CreateClassRoomArgs";
import { UpdateClassRoomArgs } from "./UpdateClassRoomArgs";
import { DeleteClassRoomArgs } from "./DeleteClassRoomArgs";
import { ClassRoomFindManyArgs } from "./ClassRoomFindManyArgs";
import { ClassRoomFindUniqueArgs } from "./ClassRoomFindUniqueArgs";
import { ClassRoom } from "./ClassRoom";
import { UserFindManyArgs } from "../../user/base/UserFindManyArgs";
import { User } from "../../user/base/User";
import { ClassRoomService } from "../classRoom.service";

@graphql.Resolver(() => ClassRoom)
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
export class ClassRoomResolverBase {
  constructor(
    protected readonly service: ClassRoomService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "ClassRoom",
    action: "read",
    possession: "any",
  })
  async _classRoomsMeta(
    @graphql.Args() args: ClassRoomFindManyArgs
  ): Promise<MetaQueryPayload> {
    const results = await this.service.count({
      ...args,
      skip: undefined,
      take: undefined,
    });
    return {
      count: results,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [ClassRoom])
  @nestAccessControl.UseRoles({
    resource: "ClassRoom",
    action: "read",
    possession: "any",
  })
  async classRooms(
    @graphql.Args() args: ClassRoomFindManyArgs
  ): Promise<ClassRoom[]> {
    return this.service.findMany(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => ClassRoom, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "ClassRoom",
    action: "read",
    possession: "own",
  })
  async classRoom(
    @graphql.Args() args: ClassRoomFindUniqueArgs
  ): Promise<ClassRoom | null> {
    const result = await this.service.findOne(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => ClassRoom)
  @nestAccessControl.UseRoles({
    resource: "ClassRoom",
    action: "create",
    possession: "any",
  })
  async createClassRoom(
    @graphql.Args() args: CreateClassRoomArgs
  ): Promise<ClassRoom> {
    return await this.service.create({
      ...args,
      data: args.data,
    });
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => ClassRoom)
  @nestAccessControl.UseRoles({
    resource: "ClassRoom",
    action: "update",
    possession: "any",
  })
  async updateClassRoom(
    @graphql.Args() args: UpdateClassRoomArgs
  ): Promise<ClassRoom | null> {
    try {
      return await this.service.update({
        ...args,
        data: args.data,
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => ClassRoom)
  @nestAccessControl.UseRoles({
    resource: "ClassRoom",
    action: "delete",
    possession: "any",
  })
  async deleteClassRoom(
    @graphql.Args() args: DeleteClassRoomArgs
  ): Promise<ClassRoom | null> {
    try {
      return await this.service.delete(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => [User])
  @nestAccessControl.UseRoles({
    resource: "User",
    action: "read",
    possession: "any",
  })
  async users(
    @graphql.Parent() parent: ClassRoom,
    @graphql.Args() args: UserFindManyArgs
  ): Promise<User[]> {
    const results = await this.service.findUsers(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }
}
