/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/docs/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { CertificationUpdateManyWithoutUsersInput } from "./CertificationUpdateManyWithoutUsersInput";
import { ValidateNested, IsOptional, IsString } from "class-validator";
import { Type } from "class-transformer";
import { ClassRoomWhereUniqueInput } from "../../classRoom/base/ClassRoomWhereUniqueInput";
import { NotePaperUpdateManyWithoutUsersInput } from "./NotePaperUpdateManyWithoutUsersInput";
@InputType()
class UserUpdateInput {
  @ApiProperty({
    required: false,
    type: () => CertificationUpdateManyWithoutUsersInput,
  })
  @ValidateNested()
  @Type(() => CertificationUpdateManyWithoutUsersInput)
  @IsOptional()
  @Field(() => CertificationUpdateManyWithoutUsersInput, {
    nullable: true,
  })
  certifications?: CertificationUpdateManyWithoutUsersInput;

  @ApiProperty({
    required: false,
    type: () => ClassRoomWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => ClassRoomWhereUniqueInput)
  @IsOptional()
  @Field(() => ClassRoomWhereUniqueInput, {
    nullable: true,
  })
  classRoom?: ClassRoomWhereUniqueInput | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  firstName?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  lastName?: string | null;

  @ApiProperty({
    required: false,
    type: () => NotePaperUpdateManyWithoutUsersInput,
  })
  @ValidateNested()
  @Type(() => NotePaperUpdateManyWithoutUsersInput)
  @IsOptional()
  @Field(() => NotePaperUpdateManyWithoutUsersInput, {
    nullable: true,
  })
  notePapers?: NotePaperUpdateManyWithoutUsersInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  password?: string;

  @ApiProperty({
    required: false,
    type: [String],
  })
  @IsString({
    each: true,
  })
  @IsOptional()
  @Field(() => [String], {
    nullable: true,
  })
  roles?: Array<string>;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  username?: string;
}
export { UserUpdateInput };
