/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/docs/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { CertificationCreateNestedManyWithoutUsersInput } from "./CertificationCreateNestedManyWithoutUsersInput";
import { ValidateNested, IsOptional, IsString } from "class-validator";
import { Type } from "class-transformer";
import { NotePaperCreateNestedManyWithoutUsersInput } from "./NotePaperCreateNestedManyWithoutUsersInput";
@InputType()
class UserCreateInput {
  @ApiProperty({
    required: false,
    type: () => CertificationCreateNestedManyWithoutUsersInput,
  })
  @ValidateNested()
  @Type(() => CertificationCreateNestedManyWithoutUsersInput)
  @IsOptional()
  @Field(() => CertificationCreateNestedManyWithoutUsersInput, {
    nullable: true,
  })
  certifications?: CertificationCreateNestedManyWithoutUsersInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  firstName?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  lastName?: string | null;

  @ApiProperty({
    required: false,
    type: () => NotePaperCreateNestedManyWithoutUsersInput,
  })
  @ValidateNested()
  @Type(() => NotePaperCreateNestedManyWithoutUsersInput)
  @IsOptional()
  @Field(() => NotePaperCreateNestedManyWithoutUsersInput, {
    nullable: true,
  })
  notePapers?: NotePaperCreateNestedManyWithoutUsersInput;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @Field(() => String)
  password!: string;

  @ApiProperty({
    required: true,
    type: [String],
  })
  @IsString({
    each: true,
  })
  @Field(() => [String])
  roles!: Array<string>;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @Field(() => String)
  username!: string;
}
export { UserCreateInput };
