/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/docs/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as graphql from "@nestjs/graphql";
import * as apollo from "apollo-server-express";
import * as nestAccessControl from "nest-access-control";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { CreateSyllabusArgs } from "./CreateSyllabusArgs";
import { UpdateSyllabusArgs } from "./UpdateSyllabusArgs";
import { DeleteSyllabusArgs } from "./DeleteSyllabusArgs";
import { SyllabusFindManyArgs } from "./SyllabusFindManyArgs";
import { SyllabusFindUniqueArgs } from "./SyllabusFindUniqueArgs";
import { Syllabus } from "./Syllabus";
import { SyllabusService } from "../syllabus.service";

@graphql.Resolver(() => Syllabus)
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
export class SyllabusResolverBase {
  constructor(
    protected readonly service: SyllabusService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "Syllabus",
    action: "read",
    possession: "any",
  })
  async _syllabiMeta(
    @graphql.Args() args: SyllabusFindManyArgs
  ): Promise<MetaQueryPayload> {
    const results = await this.service.count({
      ...args,
      skip: undefined,
      take: undefined,
    });
    return {
      count: results,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [Syllabus])
  @nestAccessControl.UseRoles({
    resource: "Syllabus",
    action: "read",
    possession: "any",
  })
  async syllabi(
    @graphql.Args() args: SyllabusFindManyArgs
  ): Promise<Syllabus[]> {
    return this.service.findMany(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => Syllabus, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "Syllabus",
    action: "read",
    possession: "own",
  })
  async syllabus(
    @graphql.Args() args: SyllabusFindUniqueArgs
  ): Promise<Syllabus | null> {
    const result = await this.service.findOne(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Syllabus)
  @nestAccessControl.UseRoles({
    resource: "Syllabus",
    action: "create",
    possession: "any",
  })
  async createSyllabus(
    @graphql.Args() args: CreateSyllabusArgs
  ): Promise<Syllabus> {
    return await this.service.create({
      ...args,
      data: args.data,
    });
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Syllabus)
  @nestAccessControl.UseRoles({
    resource: "Syllabus",
    action: "update",
    possession: "any",
  })
  async updateSyllabus(
    @graphql.Args() args: UpdateSyllabusArgs
  ): Promise<Syllabus | null> {
    try {
      return await this.service.update({
        ...args,
        data: args.data,
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Syllabus)
  @nestAccessControl.UseRoles({
    resource: "Syllabus",
    action: "delete",
    possession: "any",
  })
  async deleteSyllabus(
    @graphql.Args() args: DeleteSyllabusArgs
  ): Promise<Syllabus | null> {
    try {
      return await this.service.delete(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
